"""User & Order creation dates added

Revision ID: 8f5a3bb10566
Revises: bb4ac2ade3b7
Create Date: 2023-08-03 09:52:02.832562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5a3bb10566'
down_revision = 'bb4ac2ade3b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_created')
    op.drop_column('orders', 'order_created')
    # ### end Alembic commands ###
